name: Deploy to staging
on:
  push:
    branches: [ main ]

jobs:
   redeploy_everything:
    name: Deploying everything to the staging cluster
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
            script: |
                cd Monorepo-Deploy  
                git pull origin main 
                npm install -g pnpm
                pnpm install
                pnpm run build 
                npm install -g pm2
                pm2 restart fe-server 
                pm2 restart http-server 
                pm2 restart ws-serve